### ISSUE TITLE
Handshake failing with correct config

### ISSUE THREAD

**Issue by RobertD502** [goodbyepavlyi/wg-easy#9]
**Describe the bug**
Using this image instead of weejewel/wg-easy doesn't seem to work with no indication as to what the issue is in the logs.

When using this image and setting the WG_HOST to auto, I can see that the configuration file created is correct (correct ip and port). However, when attempting to use the tunnel, checking the wireguard iOS app logs shows the handshake failing. 

If I instead change back over to weejewel's image and manually set the WG_HOST, the tunnel works.

Docker Compose below:
```
  wireguard:
    image: ghcr.io/goodbyepavlyi/wg-easy
    container_name: wg-easy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    ports:
      - MY_EXTERNAL_PORT:51820/udp
      - 51821:51821/tcp
    volumes:
      - /home/robert/Docker/wg-easy:/etc/wireguard
    environment:
      - WG_HOST=auto
      - PASSWORD=MY_PASSWORD
      - WG_PORT=MY_EXTERNAL_PORT
    restart: always
```

As mentioned before, nothing sticks out/no failures logged in the wg-easy container logs.
